In [7]:
import sys
sys.path.append('../')

from water_body_finder import find_waterbody_mask, extract_features
import rasterio
from rasterio.plot import reshape_as_image
import pickle
import pandas as pd
from PIL import Image
import matplotlib.pyplot as plt

In [2]:
# define paramets

image_data_dir = "C:\\personal\\satalite-image-water-body-finder\\data\image_data\\2628BB01.tif"
rfc_dir = "C:\\personal\\satalite-image-water-body-finder\\data\\rfc\\rfc_1.p"

In [3]:
# load data

raster_image_data = rasterio.open(image_data_dir).read()
image_data = reshape_as_image(raster_image_data)


In [4]:
# load rfc

f = open(rfc_dir, 'rb')
rfc = pickle.load(f)

predict = rfc.predict(pd.DataFrame({
    'variance_a': [5, 5],
    'variance_b': [5, 5]
}))

print(type(predict))

<class 'numpy.ndarray'>


In [5]:
result = find_waterbody_mask(image_data, rfc, 5, 15)

In [6]:
print(result)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [10]:
img = Image.fromarray(result * 255)
img.save('test.png')